### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by g101418** [sunlab-osu/TURL#1]
The error occurred on model/transformers/__init__.py

ModuleNotFoundError   No module named 'model.transformers.data'

**Comment by ikhan94** [comment]
> The error occurred on model/transformers/**init**.py
> 
> ModuleNotFoundError No module named 'model.transformers.data'

Hey,

did u solved that issue?
If, yes can u let me know how u solved it.

**Comment by xiang-deng** [comment]
Those files are from huggingface transformers. These missing files are actually not used but if necessary you should be able to just copy from the official repo.
