### ISSUE TITLE
data subdir missing from model.transformers

### ISSUE THREAD

**Issue by alex-bogatu** [sunlab-osu/TURL#10]
Hi,
I am trying to get the evaluate_task notebook running and I am facing some issues.

```
/content/TURL/model/transformers/__init__.py in <module>()
     23                          is_tf_available, is_torch_available)
     24 
---> 25 from .data import (is_sklearn_available,
     26                    InputExample, InputFeatures, DataProcessor,
     27                    glue_output_modes, glue_convert_examples_to_features,

ModuleNotFoundError: No module named 'model.transformers.data'
```

It seems that the data directory is missing from model.transformers. Any suggestions? Thanks!

**Comment by kimlindner** [comment]
Hi, 
I am having the same issue. 

Is there any update yet?

**Comment by xiang-deng** [comment]
Hi sorry I forgot to reply here. The data dir from transformers is ignored while pushing the code because of the configuration in .gitignore. You can simply copy the dir from the official transformers repo or pull the latest commit that fixes this. Thanks.
