### ISSUE TITLE
"Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?"

### ISSUE THREAD

**Issue by canqin001** [sunlab-osu/TURL#12]
Hi. When I try to use "docker pull xdeng/transformers:latest", there is an error as "Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?". Do you have any ideas to address it? Thanks!

**Comment by xiang-deng** [comment]
This seems to be a problem with your docker installation. Please make sure your docker daemon is running properly. Thanks.
