### ISSUE TITLE
Instruction for preparing code from original WikiTable Corpus

### ISSUE THREAD

**Issue by g1644222** [sunlab-osu/TURL#14]
I would like to replicate your study with my own data.
Would you be willing to show me how to do this?

**Comment by huan-sunrise** [comment]
Can you be more specific about issues you ran into when doing that? For example, did you first try one task (e.g., entity linking, column type prediction)? What problems did you come across?

**Comment by xiang-deng** [comment]
If you just want to get the representation of your own tables, you can either transform the data to the same format as *[split]_tables.jsonl* and use our dataloader, or refer to the example given in `evaluate_task.ipynb` from cell 8, which we show how to  construct the input from an arbitrary table and get the representation. The representation can then be used for tasks like classification or matching. Note that entity linking is not necessary, you can leave it empty. The model can get representation with only cell values.

**Comment by g1644222** [comment]
Thanks for the quick response.

I would like to know how to make [split]_tables.jsonl from the original WikiTables corpus.
In the readme, it says "TODO: Instruction for preparing code from original WikiTable Corpus" and I could not reproduce it.

I'm sorry if I didn't check enough, but is the program to make [split]_tables.jsonl available to the public?
If not, I would like to see it published on github.

**Comment by xiang-deng** [comment]
No, we do not include the script to generate the `[split]_tables.jsonl` file. Some of the scripts used to preparing data for downstream tasks have been included. The original WikiTables data contains most of the info (cleaned row&col, Wikipedia links, caption etc) needed. What we did is mostly filtering to extract dense entity tables. You can refer to section 5.1 in our paper for more information.

**Comment by g1644222** [comment]
Thanks for the reply.
I will try to make one based on your paper.

Thank you for responding!
