### ISSUE TITLE
Cannot load data in the jupyter notebook evaluate_task.ipynb

### ISSUE THREAD

**Issue by ysunbp** [sunlab-osu/TURL#16]
For the first task, when executing: dataset = WikiHybridTableDataset(data_dir,entity_vocab,max_cell=100, max_input_tok=350, max_input_ent=150, src="dev", max_length = [50, 10, 10], force_new=False, tokenizer = None, mode=0). It will trigger an error leading to /data_loader/hybrid_data_loaders.py line 424: int() argument must be a string, a bytes-like object or a number not 'NoneType'. 
I checked the code for this line and it's like: processed_data = list(tqdm(pool.imap(partial(process_single_hybrid_table,config=self), actual_tables, chunksize=2000),total=len(actual_tables))). I wonder if there's a typo here or if there are any problems in the data? If so, how should we fix it? 
Thanks!
![e940216daeaec31f74b303930306ddb](https://user-images.githubusercontent.com/41725714/134147754-50ac89e1-4a90-4c6c-80ce-2d6309f34a04.png)

**Comment by xiang-deng** [comment]
I just tried to run the cell in `evaluate_task.ipynb` from scratch (I removed the cached preprocessing results) and does not run into the problem, can you try that as well.

For debugging purpose, you can try to remove the multiprocessing part (`pool.imap`) and just loop over the data so you can get a more precise error message.

**Comment by ysunbp** [comment]
Thanks! I think I have located the bug. In /data_loader/hybrid_data_loaders.py I changed line 443 from self.tokenizer = BertTokenizer.from_pretrained('data/pre-trained_models/bert-base-uncased') into self.tokenizer = BertTokenizer.from_pretrained('bert-base-uncased'), and the problem is solved.
Initially I think the vocab.txt file is the entity_vocab.txt file and I simply copy it to the directory 'data/pre-trained_models/bert-base-uncased/', which turns out to be incorrect.
Thanks again for your kind reply!

**Comment by shraga89** [comment]
Hi I am also trying to run evaluate_task.ipynb. However, I couldn't find the file "entity_vocab.txt" in the published data repository (https://osu.app.box.com/s/qqpdn4hbgjaiw2twn58aikqsxtxrwi2t/folder/121487598337). So I can't run this cell (since entity_vocab is missing). I also did not find "dev_tables.jsonl" which is also used in that cell. 

Thanks!

**Comment by xiang-deng** [comment]
There are multiple pages in the box share, you should be able to find them in the second page.

**Comment by shraga89** [comment]
Thanks! your help is much appreciated!
