### ISSUE TITLE
How to create dataset for Column Type Annotation?

### ISSUE THREAD

**Issue by yuji-mizobuchi** [sunlab-osu/TURL#17]
Hello, Thank you for sharing your great work. I am currently trying to create training data for Column Type Annotation. According to your paper, you mentioned the data was created in a way that "we only keep columns in our relational table corpus that have at least 3 linked entities to Freebase". So I tried to extract tables from the [TabEL data](http://websail-fe.cs.northwestern.edu/TabEL/) that had at least three links to Freebase. However, as far as I examined, there were no such links in TabEL. Could you please tell me how to extract tables for  Column Type Annotation?

**Comment by xiang-deng** [comment]
Hi, the original TabEL data only contain wikipedia hyperlinks, which are unique identifiers for wikipedia pages. There are one-to-one mappings between freebase entities (or dbpedia/wikidata depending on which KB you want to use), you can check this https://stackoverflow.com/questions/41236503/entity-name-not-found-by-its-mid-in-freebase
