### ISSUE TITLE
the end of train.table_col_type.json

### ISSUE THREAD

**Issue by zsy-98** [sunlab-osu/TURL#19]
Hi,
It seems that "train.table_col_type.json" dose not end normally and contains 215, 954 tables. The picture below is the end of the file. Could you please update that file? In paper there are 397, 098 tables for training.
<img width="572" alt="image" src="https://user-images.githubusercontent.com/52916581/205441283-4ff831f6-ebd6-484c-836d-c3060789880d.png">
Best regards,
zsy

**Comment by xiang-deng** [comment]
Hi, I just downloaded `train.table_col_type.json` and seems it is not corrupted. The end of the file is 
```json
                        1348633,
                        "HC Davos"
                    ]
                ],
                [
                    [
                        9,
                        1
                    ],
                    [
                        1348633,
                        "HC Davos"
                    ]
                ]
            ]
        ],
        [
            [
                "sports.pro_athlete",
                "people.person"
            ],
            [
                "sports.sports_team",
                "organization.organization"
            ]
        ]
    ]
]
```
Can you try to download it again? Let me know if you still have any issues.
