### ISSUE TITLE
Extracting the pretrained Embeddings for a csv table

### ISSUE THREAD

**Issue by SvenGroen** [sunlab-osu/TURL#20]
Hi,
I am thinking about testing out TURL for a project I am working on where I test different tabular preprocessing mechanisms and was thinking about testing TURLs pretrained embeddings.

Is there an easy way to extract the pretrained embeddings for a given csv row?

for example data like the [adult income dataset](https://www.kaggle.com/datasets/wenruliu/adult-income-dataset):

```
from catboost.datasets import adult
adult_train, adult_test = adult()

print(adult_train.head(3))
```

```
    age         workclass    fnlwgt  education  education-num      marital-status         occupation   relationship   race   sex  capital-gain  capital-loss  hours-per-week native-country income
0  39.0         State-gov   77516.0  Bachelors           13.0       Never-married       Adm-clerical  Not-in-family  White  Male        2174.0           0.0            40.0  United-States  <=50K
1  50.0  Self-emp-not-inc   83311.0  Bachelors           13.0  Married-civ-spouse    Exec-managerial        Husband  White  Male           0.0           0.0            13.0  United-States  <=50K
2  38.0           Private  215646.0    HS-grad            9.0            Divorced  Handlers-cleaners  Not-in-family  White  Male           0.0           0.0            40.0  United-States  <=50K
```

I looked at `evaluate_task.ipynb` and the "Pretrained and CF"-section but am somewhat lost since I have never worked on CF or the wikitables dataset.

Is there an easy way to get the embedding representations of a csv table, where I don't have additional information like "page-title", “section title”, etc.?

Best,
Sven

**Comment by xiang-deng** [comment]
Hi. I recently helped with a table imputation task where they also used the adult income dataset (and some other csv tables traditionally used for data mining). My observation was that using pretrained TURL embedding directly does not work very well, as the model is only pretrained on entity-focused Wikipedia tables (e.g., only seen very few numeric values). However, the model can still achieve decent performance after tuning for a specific task. In their case, it is predicting missing cell values.

Can you elaborate more on whether you want to get the embedding for a specific cell, a row, or a column? More specifically,
1. It is fine to miss a few elements. We have ablations in the paper about removing certain input components, e.g., title, header, and particularly entity embedding. You can just put a default value there, see [here](https://github.com/sunlab-osu/TURL/blob/bfec92e942a648695b3910aab42a6f0b679d37fc/run_table_CT_finetuning.py#L176) for an example of how we did this for column type experiments.
2. If you want to get column embeddings, I would suggest checking the column type classification task
3. If you want to get cell embedding, cell filling should be enough, replace the target cell with [MASK] and get its embedding
4. We don't really have a row-wise task so don't have a row  representation. The closest that I can think of is to extract all cell embeddings in that row and do a mean/max pooling.

**Comment by xiang-deng** [comment]
There is also a [helper function](https://github.com/sunlab-osu/TURL/blob/bfec92e942a648695b3910aab42a6f0b679d37fc/data_loader/hybrid_data_loaders.py#L789) to construct input to the model with an arbitrary table that you can use to get embedding from a vanilla pretrained model. For fields that you don't have you should be able to just put in None or use some default value.

**Comment by SvenGroen** [comment]
Hi, thank you for the fast and elaborate answer.
I am currently working on tabular data synthesis with diffusion models for my master's thesis (and hopefully publishable paper later on).
I basically test different ways to represent tabular data and see if they improve the generation of realistic tabular data.
I already found an [approach that uses static embeddings](https://github.com/pfnet-research/CSDI_T/blob/d7655578d51b062fefb16656ba635478b458c92d/src/main_model_table_ft.py), but I would also like to try out learned embeddings.

My model expects a 1 dim representation of rows [bs, #features] / [bs, #columns].

Another challenge is that I also have to reverse this process (Given a (synthetic) embedding representation, get the original row representation).
I was thinking about getting an embedding representation for each cell entry (e.g. age = 39) in a given row, get the embedding representations for the other entries in the row and concatenate all representations, so I have a representation of a row.

For the reverse process, I was thinking about selecting the closest token in the embedding space for each of my cell in my synthetic embedding.

At the moment it's just an idea I have, and I am looking through the literature and testing different pretrained tabular embedding models to see if I can find one where I can easily implement this experiment 😄
