### ISSUE TITLE
Can't run pre-training

### ISSUE THREAD

**Issue by Deryuu** [sunlab-osu/TURL#21]
Hello, i just want to run the pre-training for TURL but i have several problems. 
I tried to run pre_train.sh, pre_train_hybrid.sh and pre_train_hybrid_v2.sh.

Executing pre_train.sh and pre_train_hybrid.sh gives me following error:

`Traceback (most recent call last):
  File "run_table_lm_finetuning.py", line 757, in <module>
    main()`
  `File "run_table_lm_finetuning.py", line 675, in main
    new_ent_embeddings = create_ent_embedding(args.data_dir, entity_wikid2id, origin_ent_embeddings)`
  `File "/pfs/data5/home/ma/ma_ma/ma_tuvu/workspace/turl/utils/util.py", line 58, in create_ent_embedding
    origin_embed[ent_vocab[wiki_id]] = ent_embed[str(wiki_id)]
IndexError: index 368793 is out of bounds for axis 0 with size 368793`

I know this is due to the "ent_vocab_size" parameter in the "table-base-config.json". Do you use a different entity_vocab.txt than in your shared box?

For pre_train_hybrid_v2.sh i get following error:

`Traceback (most recent call last):
  File "run_hybrid_table_lm_finetuning.py", line 790, in <module>
    main()`
  `File "run_hybrid_table_lm_finetuning.py", line 728, in main
    global_step, tr_loss = train(args, config, train_dataset, model, eval_dataset=eval_dataset, sample_distribution=sample_distribution)`
  `File "run_hybrid_table_lm_finetuning.py", line 161, in train
    for step, batch in enumerate(epoch_iterator):`
  `File "/home/ma/ma_ma/ma_tuvu/miniconda3/envs/turl-2/lib/python3.6/site-packages/tqdm/std.py", line 1129, in __iter__
    for obj in iterable:`
  `File "/home/ma/ma_ma/ma_tuvu/miniconda3/envs/turl-2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 521, in __next__
    data = self._next_data()`
  `File "/home/ma/ma_ma/ma_tuvu/miniconda3/envs/turl-2/lib/python3.6/site-packages/torch/utils/data/dataloader.py", line 561, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration`
  `File "/home/ma/ma_ma/ma_tuvu/miniconda3/envs/turl-2/lib/python3.6/site-packages/torch/utils/data/_utils/fetch.py", line 52, in fetch
    return self.collate_fn(data)`
  `File "/pfs/data5/home/ma/ma_ma/ma_tuvu/workspace/turl/data_loader/hybrid_data_loaders.py", line 567, in __call__
    raise Exception
Exception`

I don't really know how to handle this error, i know it comes from this line in the hybrid_data_loader.py:

` if batch_entity_cand[0] is None and self.use_cand:
        raise Exception`

I hope you can help me, and thank you in advance.

**Comment by xiang-deng** [comment]
Hi sorry for the delay in response.

For the first question, the released final model and data are used for hybrid_v2, you can ignore pre_train_hybrid.

Checking the code, the exception seems to be raised by empty candidate entities. TURL used the masked entity recovery objective, and to speed up the training I prepared the entity candidates in advance. You can see in https://github.com/sunlab-osu/TURL/blob/bfec92e942a648695b3910aab42a6f0b679d37fc/data_loader/hybrid_data_loaders.py#L297-L317 that the model tries to load the cached entity candidates and use them for pre-training, can you check the location of those files again?

**Comment by Deryuu** [comment]
Thanks for the hint! I realised to delete the old pickle files and to add the .entity_candidate.pkl in the correct directory. Now it's working, thank you.
