### ISSUE TITLE
Building the term Frequency

### ISSUE THREAD

**Issue by ikhan94** [sunlab-osu/TURL#3]

**Comment by xiang-deng** [comment]
Seems I missed one line, you need to transform the collected rdd into a dictionary like the other examples.

**Comment by ikhan94** [comment]
Hi,

it worked thank you :)

**Comment by ikhan94** [comment]
<img width="1122" alt="Screenshot 2021-02-16 at 17 21 51" src="https://user-images.githubusercontent.com/55949998/108090940-7881e880-707b-11eb-9673-8d362f8dca9d.png">

**Comment by ikhan94** [comment]
Hi,

as u can see above, a new Error occurred, I tried to fix it but It gives me the same error everytime.

**Comment by xiang-deng** [comment]
I upload the CER_test_result.pkl and CER_test_result_seed_0.pkl(no seed entity) in box, which are the baseline results and can be loaded in the top-level evaluate_task notebook.
To run this baseline from scratch, seems the `row_ranking_entities.py.ipynb` is wrong and I need to upload it again. Actually, you have finished building the term frequency dictionaries after dumping all the pickle files. The cell above is for debug purpose and it is actually executed before saving the dictionaries. When saving the dictionaries the format is changed.

**Comment by ikhan94** [comment]
okay thank you very much, I just tried to create the dev_result.pkl file (row_ranking_entities.py), but unfortunately in the Docker image the Elasticsearch module is missing, could you please add this.

**Comment by xiang-deng** [comment]
Elasticsearch is required by the table augmentation baselines, you can find the original implementation [here](https://github.com/iai-group/sigir2017-table). They suggest 

> using elastic 2 ( > 2.3)

You can find the proper docker image in dockerhub, I was using elasticsearch:2
