### ISSUE TITLE
Code about visibility matrix

### ISSUE THREAD

**Issue by Thanksyy** [sunlab-osu/TURL#6]
Hi, it seems that I can not find the related codes about the visibility matrix, could you point them out?

**Comment by xiang-deng** [comment]
The visibility matrix is passed to the model as `input_tok_mask` and `input_ent_mask` and used as attention masks. You can find the code in [data_loaders](https://github.com/sunlab-osu/TURL/blob/90cde26a3cf58b0ad42599155726e749c060d177/data_loader/hybrid_data_loaders.py#L120)
